language: python
python:
  - "2.7"
before_script:
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install lxml
  - pip install pluginbase
script:
  - coverage run -m py.test android-runner/tests/unit --cov android-runner
after_success:
  - coveralls
